site_name: wiki
site_url: https://samperay.github.io/wiki/
nav:
        - Home: index.md
        - "programming":
                  - "python":
                            - "design patterns":
                                      - "Solid principles" : "programming/python/design_patterns/solid_principles.md"
                                      - "Adapter": "programming/python/design_patterns/adapter.md"
                                      - "Bridge": "programming/python/design_patterns/bridge.md"
                                      - "Builder": "programming/python/design_patterns/builder.md"
                                      - "Builder facet": "programming/python/design_patterns/builder-facet.md"
                                      - "Composite": "programming/python/design_patterns/composite.md"
                                      - "Decorator": "programming/python/design_patterns/decorators.md"
                                      - "Factory Methods": "programming/python/design_patterns/factory-method.md"
                                      - "Prototype": "programming/python/design_patterns/prototype.md"
                                      - "Singleton": "programming/python/design_patterns/singleton.md"
                                      - "Observer" : "programming/python/design_patterns/observer.md"
                                      
                            - "data structures":
                                      - "overview": "programming/python/data_structures/overview.md"
                                      - "linked list": "programming/python/data_structures/linked_list.md"
                                      - "sorting": "programming/python/data_structures/sorting.md"
                                      - "stacks": "programming/python/data_structures/stacks.md"
                                      - "queues": "programming/python/data_structures/queues.md"
                                      - "recursions": "programming/python/data_structures/recursions.md"
                                      - "trees": "programming/python/data_structures/trees.md"
                                      - "hashing": "programming/python/data_structures/hashing.md"

                            - "webapp framework":
                                      - "fastapi": "programming/python/webapp_framework/fastapi/fastapi.md"
                                      - "flask": "programming/python/webapp_framework/flask/flask.md"

                            - "advance concepts":
                                      - "oops": programming/python/oops.md
                                      - "concepts": "programming/python/concepts.md"
                                      
                            - "interviews":
                                      - "Q&A": "programming/python/qa.md"

                  - "clean code":
                            - "overview": "programming/clean_code/overview.md"
                            - "naming" : "programming/clean_code/naming.md"
                            - "structure": "programming/clean_code/structure.md"
                            - "func methods": "programming/clean_code/methods.md"
                            - "control structures": "programming/clean_code/control_structure.md"
                            - "oop principles": "programming/clean_code/ooo.md"
                  - "pandas": 
                            - "overview": "programming/pandas/overview.md"

                  - "go":
                            - "overview": "programming/go/overview.md"
                            - "basics": "programming/go/basics.md"
                            - "interviews faq": programming/go/interviews.md
        - "database":
                  - "postgresql":
                            - "setup and install": "db/postgresql/install.md"

        - "docker_k8": 
                  - "docker":
                        - "Overview": "docker_k8/docker/overview.md"
                        - "FAQ": "docker_k8/docker/faq.md"
                  - "k8":
                        - "architecture": "docker_k8/k8/architecture.md"
                        - "kube reference": "docker_k8/k8/cmdref.md"
                        - "core concepts": "docker_k8/k8/core.md"
                        - "scheduling": "docker_k8/k8/scheduling.md"
                        - "networking": "docker_k8/k8/networking.md"
                        - "storage": "docker_k8/k8/storage.md"
                        - "applifecyclemgmt": "docker_k8/k8/applifecyclemgmt.md"
                        - "clustermaintenance": "docker_k8/k8/clustermaintenance.md"
                        - "security": "docker_k8/k8/security.md"
                        - "troubleshooting": 
                                - "issues": "docker_k8/k8/troubleshooting/issues.md"
                                - "overview": "docker_k8/k8/troubleshooting/overview.md"
                  - "istio": 
                        - "Overview": "docker_k8/istio/istio_overview.md"
                        - "Traffic Mgmt": "docker_k8/istio/traffic_mgmt.md"

        - "cicd":
                  - "Overview": "cicd/overview.md"
                  - "github actions":
                            - "Overview": "cicd/github_actions/overview.md"
                            - "Introduction": "cicd/github_actions/intro.md"
                            - "Triggers": "cicd/github_actions/workflow_triggers.md"
                            - "Variables": "cicd/github_actions/variables.md"
                            - "Matrix stratergy": "cicd/github_actions/matrix_strategy.md"
                            - "CICD pipeline": "cicd/github_actions/cicd.md"
                  - "jenkins":
                            - "Overview": "cicd/jenkins/overview.md"
                            - "deploy": "cicd/jenkins/deploy.md"
                  - "tekton":
                            - "overview": "cicd/tekton/overview.md"
                            - "concepts": "cicd/tekton/concepts.md"
                            - "pipelines": "cicd/tekton/tasks_pipelines.md"
                  - "argocd":
                            - "overview": "cicd/argocd/overview.md"
                            - "install": "cicd/argocd/install.md"
                            - "applications": "cicd/argocd/applications.md"
                            - "sync": "cicd/argocd/sync.md"
                            - "faq": "cicd/argocd/faq.md"

        - "vcontroller":
                  - "Overview": "vcontroller/git/overview.md"
                  - "faq": "vcontroller/git/faq.md"

        - "monitoring":
                - "elk":
                        - "elasticsearch":
                                - "setup and install": "monitoring/elk/elasticsearch/01_install.md"
                                - "managing documents": "monitoring/elk/elasticsearch/02_managing_docs.md"
                                - "mapping and analysis": "monitoring/elk/elasticsearch/03_mapping_analysis.md"
                        - "logstash":
                                - "overview": monitoring/elk/logstash/overview.md

                        - "kibana":
                                - "overview": monitoring/elk/kibana/overview.md

        - "linux":
                - "administration":
                        - "basic": "linux/admin/basics.md"
                        - "network": "linux/admin/networking.md"
                        - "storage": "linux/admin/storage.md"
                        - "security": "linux/admin/security.md"
                        - "booting issue": "linux/admin/troubleshooting.md"

                - "scripting":
                        - "overview": "linux/scripting/overview.md"
                        - "faq": "linux/scripting/faq.md"
                        - "hackerrank": linux/scripting/hackerrank.md

                - "ansible":
                        - "install": "linux/ansible/install.md"
                        - "overview": "linux/ansible/overview.md"
                        

                  
        - "sysdesign":
                  - "Architecture process": sysdesign/arch_process.md
                  - "Selecting a database": sysdesign/selectingdb.md
                  - "Design newsletter": sysdesign/papersource.md
                  - "Design Autonomous cars" : sysdesign/autonomouscars.md
                  - "Design gross collections": sysdesign/grosscollections.md
                  - "Payment processing": sysdesign/paymentprocessing.md
                  - "Airbnb": sysdesign/airbnb.md
                  - "Amazon": sysdesign/amazon.md
                  - "Facebook": sysdesign/facebook.md
                  - "Google Maps": sysdesign/gmaps.md
                  - "Notification service": sysdesign/notifications.md
                  - "Twitter": sysdesign/twitter.md
                  - "Uber": sysdesign/uber.md
                  - "Whatsapp": sysdesign/whatsapp.md
                  - "Youtube": sysdesign/youtube.md
                  - "URL Shortner": sysdesign/url_shortner.md
                  - "Zoom": sysdesign/zoom.md
                  

        - "cloud": 
                  - "ibm": 
                        - "IBM Professional Cloud Developer Overview": "cloud/ibm/ibm_professional_cloud_developer.md"
                        - "IBM Automation Tools": "cloud/ibm/automated_dev_tools.md"
                        - "IBM application Deployment": "cloud/ibm/application_deployment.md"
                        - "IBM Cloud Schematics": "cloud/ibm/cloud_schematics.md"
                  - "aws":
                        - "practitioner":
                                - "Summary": "cloud/aws/practitioner/summary.md"
                                

                  - "terraform":
                        - "overview": "cloud/terraform/overview.md"
                        - "study guide" : "cloud/terraform/study_guide.md"
                        - "faq": "cloud/terraform/faq.md"
                        

        - "secretmgmt":
                - "vault": 
                        - "introduction": "secretmgmt/vault/vault_overview.md"
                        - "architecture": "secretmgmt/vault/vault_architecture.md"
                        - "auth methods": "secretmgmt/vault/auth_methods.md"
                        - "policies" : "secretmgmt/vault/policies.md"
                        - "access token": "secretmgmt/vault/access_vault_token.md"
                        - "secret engine": "secretmgmt/vault/secret_engine.md"
                        - "agent": "secretmgmt/vault/vault_agent.md"
                        - "replication": "secretmgmt/vault/vault_replication.md"


        - "ds_ai_ml":
                - "data science":
                        - "Overview": "ds_ai_ml/ds/overview.md"
                
                - "AI":
                        - "Overview": "ds_ai_ml/ai/overview.md"
                        - "text summarization": "ds_ai_ml/ai/text_summariztion.md"
                        - "movie poster": "ds_ai_ml/ai/movie_poster.md"
                        - "chatbot": "ds_ai_ml/ai/chatbot.md"
                        
                - "mlops": 
                        - Overview: "ds_ai_ml/mlops/overview.md"
                        - "Introduction": "ds_ai_ml/mlops/introduction.md"
                        - "Data":  "ds_ai_ml/mlops/data.md"
                        - "Models": "ds_ai_ml/mlops/models.md"
                        - "Insurance Claim": "ds_ai_ml/mlops/project.md"
                        - "Security": "ds_ai_ml/mlops/security_gov.md"
                        - "AWS sagemaker": "ds_ai_ml/mlops/aws_sage_maker.md"

        - "nginx":
                - "web server": "nginx/webserver_overview.md"
                - "http protocol": "nginx/http_protocol.md"
                - "nginx overview": "nginx/nginx_overview.md"
                - "load balancer": "nginx/load_balancer.md"
                - "caching": "nginx/caching.md"
                - "static assets": "nginx/static_assets.md"
                - "logging": "nginx/logging.md"
                - "http compression": "nginx/http_compression.md"
                - "access control": "nginx/access_control.md"
                - "cryptography": "nginx/cryptography.md"
                - "reverse proxy": "nginx/reverse_proxy.md"
        - "SRE":
                - "Overview": "sre/overview.md"
                - "SRE measurements": "sre/sre_measure.md"
                - "Managing complexity": "sre/manage_complexity.md"
                - "Incident Management": "sre/incident_management.md"
                - "Release Engineering": "sre/release_engineering.md"
                - "Chaos Engineering": "sre/chaos_engineering.md"
                - "Observability": "sre/observability.md"
                

        - "softskills":
                - "Overview": "softskills/overview.md"
                - "leadership": "softskills/leadership.md"

        - "kafka": 
                - "Overview": "kafka/overview.md"
                
    
        - "jobdesc":
                - "sre": "jobdesc/sre.md"
                - "devops": "jobdesc/devops.md"
                - "srdevops": "jobdesc/srdevops.md"
                          
        - about: about.md
theme:
        name: material
        features:
                # - toc.integrate
                # - navigation.tabs
                - navigation.section
                - navigation.path
                - navigation.top
                - search.suggest
                - search.highlight
                - content.tabs.link
                - content.code.annotation
                - content.code.copy
                - header.autohide
        language: en
        palette:
                - scheme: default
                  toggle:
                          icon: material/weather-night
                          name: Switch to dark mode

                # Palette toggle for dark mode
                - scheme: slate
                  toggle:
                          icon: material/weather-sunny
                          name: Switch to light mode
        font:
                text: Roboto Mono
